//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTaiBaoCaoTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduationReport
    {
        public int GraduationReportID { get; set; }
        public string GraduationReportName { get; set; }
        public string Image { get; set; }
        public string ReportFile { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public Nullable<int> CommentID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
