//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTaiBaoCaoTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduationReport
    {
        public int GraduationReportID { get; set; }
        public string GraduationReportName { get; set; }
        public string Image { get; set; }
        public int ClassID { get; set; }
        public int FacultyID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID { get; set; }
        public string Author { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string UrlFile { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> DownloadCount { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Class Class { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
