//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTaiBaoCaoTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> Role { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
