//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTaiBaoCaoTotNghiep.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Users
    {
        public int ID { get; set; }
        [DisplayName("Tên")]
        public string Name { get; set; }
        [DisplayName("Tuổi")]
        public Nullable<int> Age { get; set; }
        [DisplayName("Địa chỉ")]
        public string Address { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string UserName { get; set; }
        [DisplayName("Mật khẩu")]
        public string PassWord { get; set; }
        [DisplayName("Quyền")]
        public Nullable<int> Role { get; set; }

        public string Email { get; set; }
        [DisplayName("Điện thoại")]
        public string Phone { get; set; }
        [DisplayName("Tên lớp")]
        public Nullable<int> ClassID { get; set; }
        [DisplayName("Tên khoa viện")]
        public Nullable<int> FacultyID { get; set; }

        public Nullable<int> YearID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ResetPasswordCode { get; set; }
        [DisplayName("Niên khóa")]
        public virtual AcademicYear AcademicYear { get; set; }
        [DisplayName("Tên lớp")]
        public virtual Class Class { get; set; }
        [DisplayName("Tên khoa viện")]
        public virtual Faculty Faculty { get; set; }
    }
}
